apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: xyz-service-account
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: html
              mountPath: /var/cache/nginx/
              readOnly: false
          securityContext:
            runAsUser: 501

      volumes:
        - name: html
          emptyDir: {}
      
