apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xyz-role
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "deployments", "configmaps", "serviceaccounts", "services", "applications", "applicationsets", "appprojects"]
    verbs: ["get", "list", "watch"]
