apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1-test
  name: app1-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-test
  template:
    
    metadata:
      labels:
        app: app1-test
    spec:
      serviceAccountName: sa-ns-admin
      containers:
        - image: mnerlend/kubeshell:1
          name: alpine
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["while true; do sleep 10; done"]
        
