apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: role-ns-admin
rules:
- apiGroups:
  - ""
  resources:
  - 'pod'
  - 'deployments'
  - 'secrets'
  - 'configmaps'  
  verbs:
  - 'get'
  - 'list'
  - 'watch'
