apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2-test
  name: app2-test
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-test
  template:
    metadata:
      labels:
        app: app2-test
    spec:
      containers:
        - image: nginx:alpine
          name: nginx-alpine
          imagePullPolicy: Always
          ports:
          - containerPort: 80
  
